
export enum SearchTypes {
    START = 'SEARCH/SEARCH__START',
    PROCESS = 'SEARCH/SEARCH__PROCESS',
    END = 'SEARCH/SEARCH__END',
    ERROR = 'SEARCH/SEARCH__ERROR',
    RESET = 'SEARCH/SEARCH__RESET',
}

